import React from "react"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

import AuthService from "../api/AuthService"
import styles from "../styles/Home.module.css"

interface User {
  id: number
  email: string
  name: string
  created_at: string
  email_verified_at: string
  updated_at: string
}

function HomePage() {
  const [loadingUser, setLoadingUser] = React.useState<boolean>(true)
  const [authUser, setAuthUser] = React.useState<User | null>(null)

  React.useEffect(() => {
    AuthService.getAuthUser()
      .then(res => {
        if (res.status === 200) {
          setAuthUser(res.data)
        }
      })
      .catch(err => {
        console.log(err.response)
      })
      .finally(() => setLoadingUser(false))
  }, [])

  const logout = () => {
    AuthService.logout()
    setAuthUser(null)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <nav>
          <ul>
            <li>
              <Link href="/register">Register</Link>
            </li>
            <li>
              <Link href="/login">Login</Link>
            </li>
            <li>
              <a style={{ cursor: "pointer" }} onClick={logout}>
                Logout
              </a>
            </li>
          </ul>
        </nav>

        <p>
          {loadingUser
            ? "Loading..."
            : authUser === null
            ? "Not logged in"
            : `Logged in as ${authUser.name}`}
        </p>
      </main>
    </div>
  )
}

export default HomePage
